#!/bin/bash

# Cores
VERDE="\033[1;32m"
VERMELHO="\033[1;31m"
AZUL="\033[1;34m"
AMARELO="\033[1;33m"
ROXO="\033[1;35m"
CIANO="\033[1;36m"
RESET="\033[0m"
NEGRITO="\033[1m"

echo ""
echo ""
echo -e "${AZUL}==============================================${RESET}"
echo -e "${NEGRITO}          📖 LEGENDA DO GIT PROMPT           ${RESET}"
echo -e "${AZUL}==============================================${RESET}"
echo ""
echo -e "${AMARELO}--- ☁️  SINCRONIA COM A NUVEM (UPSTREAM) ---${RESET}"

echo -e " ${VERDE}=${RESET}   ${NEGRITO}IGUAL (Sync)${RESET}        : Tudo sincronizado. Nada para enviar ou baixar."
echo -e " ${VERMELHO}>${RESET}   ${NEGRITO}AHEAD (À Frente)${RESET}    : Você tem commits novos. Precisa de ${VERMELHO}git push${RESET}."    
echo -e " ${AMARELO}<${RESET}   ${NEGRITO}BEHIND (Atrás)${RESET}      : A nuvem tem commits novos. Precisa de ${AMARELO}git pull${RESET}."   
echo -e " ${VERMELHO}<>${RESET}  ${NEGRITO}DIVERGED (Divergiu)${RESET}: Caminhos diferentes nos dois lados. Vai precisar de Merge."
echo ""

echo -e "${AMARELO}--- 📂 ESTADO DOS ARQUIVOS (LOCAL) ---${RESET}"

echo -e " ${AZUL}%${RESET}   ${NEGRITO}UNTRACKED (${AZUL}Novo${RESET})${RESET}    : Arquivo novo que o Git ainda não conhece."
echo -e " ${VERMELHO}*${RESET}   ${NEGRITO}MODIFIED (${VERMELHO}Editado${RESET})${RESET} : Arquivo alterado, mas não adicionado. Use ${VERMELHO}git add${RESET}."
echo -e " ${VERDE}+${RESET}   ${NEGRITO}STAGED (${VERDE}Pronto${RESET})${RESET}     : Arquivo adicionado. Pronto para ${VERDE}git commit${RESET}."
echo -e " ${AMARELO}$${RESET}   ${NEGRITO}STASH (${AMARELO}Gaveta${RESET})${RESET}      : Você tem alterações guardadas com 'git stash'."    
echo ""

echo -e "${AMARELO}--- 📝 PADRÃO DE COMMIT (Conventional) ---${RESET}"
echo -e " ${NEGRITO}Formato:${RESET} <tipo>(<escopo>): <descrição>"
echo -e " ${NEGRITO}Exemplo:${RESET} feat(courses): adiciona cache local"
echo -e " ${NEGRITO}Regras :${RESET} Minúsculas, verbo imperativo, PT-BR, sem ponto final."
echo ""
echo -e " ${VERDE}feat${RESET}     : Nova funcionalidade"
echo -e " ${VERMELHO}fix${RESET}      : Correção de bug"
echo -e " ${CIANO}docs${RESET}     : Alterações em documentação"
echo -e " ${ROXO}style${RESET}    : Formatação (espaços, ponto e vírgula, etc)"
echo -e " ${AMARELO}refactor${RESET} : Mudança sem alterar comportamento (lógica)"
echo -e " ${VERDE}test${RESET}     : Adição ou correção de testes"
echo -e " ${AZUL}chore${RESET}    : Manutenção de build, deps ou ferramentas"
echo -e " ${CIANO}perf${RESET}     : Melhoria de performance"
echo ""
echo ""
